local _, L = ...;
if GetLocale() == "zhTW" then
	L.L["Last Scan"] = "最近掃描"
	L.L["Rank"] = "排名"
	L.L["Mog War"] = "幻化戰爭"
	L.L["Archive"] = "檔案"
	L.L["Winner"] = "獲勝者"
	L.L["Shared by %s: %s"] = "由 %s 分享：%s"
	L.L["Scanned %s-%s: %s"] = "掃描 %s-%s：%s"
	L.L["Show an alert in chat on a successful mog scan."] = "成功掃描幻化後在聊天中顯示提醒。"
	L.L["Scan Alerts"] = "掃描提醒"
	L.L["%d (%dW - %dL - %dC)%s"] = "%d（%d勝 - %d負 - %d比較）%s"
	L.L["Class"] = "職業"
	L.L["wins"] = "勝場"
	L.L["w"] = "勝"
	L.L["losses"] = "負場"
	L.L["l"] = "負"
	L.L["rating"] = "評分"
	L.L["rank"] = "排名"
	L.L["r"] = "排"
end
